# Generated by Django 3.2 on 2023-06-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_info_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='currency',
            field=models.CharField(choices=[('byn', 'BYN'), ('rub', 'RUB'), ('usd', 'USD'), ('eur', 'EUR')], default='byn', max_length=4, verbose_name='Валюта'),
        ),
    ]
