# Generated by Django 3.2 on 2023-07-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_dish_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='info',
            name='geolocation',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Геолокация'),
        ),
    ]
