# Generated by Django 3.2 on 2023-08-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20230802_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='heigth',
        ),
        migrations.RemoveField(
            model_name='info',
            name='width',
        ),
        migrations.AddField(
            model_name='info',
            name='latitude',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='info',
            name='longitude',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='longitude'),
        ),
    ]
