# Generated by Django 3.2 on 2023-08-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_info_was_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedinginfo',
            name='was_changed',
            field=models.DateField(auto_now=True, verbose_name='Изменено'),
        ),
    ]
