# Generated by Django 3.2 on 2023-08-20 17:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_feedinginfo_was_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='latitude',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='info',
            name='longitude',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
