# Generated by Django 3.2 on 2023-08-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20230820_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='content',
            field=models.TextField(max_length=80, verbose_name='Содержание'),
        ),
    ]
