version: "v1"

services:
  mysql:
      image: mysql:latest
      command: --default-authentication-plugin=caching_sha2_password
      restart: always
      env_file:
        - ./backend/.env
      ports:
        - '3305:3306'
      volumes:
        - db:/var/lib/mysql
        - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  django_api:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
    image: django_api
    ports: 
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - ./backend/src:/backend_app/src
      - ./backend/media:/media
    restart: always
    links:
      - mysql
    command: make up

volumes:
  db:
