# Generated by Django 3.2 on 2023-06-29 19:49

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoobject',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='photo_object', validators=[config.validators.validate_image_size], verbose_name='Файл'),
        ),
    ]
