# Generated by Django 3.2 on 2023-07-12 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0003_alter_object_pers_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='description_long',
            field=models.TextField(blank=True, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='object',
            name='pers_num',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='object',
            name='price_holiday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Цена по выходным'),
        ),
    ]
