# Generated by Django 3.2 on 2023-07-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0004_auto_20230712_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='object.object', verbose_name='Домик'),
        ),
    ]
