# Generated by Django 3.2 on 2023-07-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0005_alter_purchase_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='comment',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='count_adult',
            field=models.IntegerField(default=3, verbose_name='count of the adults'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='count_kids',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='pets',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
