# Generated by Django 3.2 on 2023-07-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0006_auto_20230725_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name="customer's comment"),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='count_kids',
            field=models.IntegerField(verbose_name='count of the children'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pets',
            field=models.TextField(blank=True, null=True, verbose_name="pet's info"),
        ),
    ]
