# Generated by Django 3.2 on 2023-07-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0007_auto_20230725_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', 'Мужской'), ('w', 'Женский')], max_length=256, null=True, verbose_name='Пол'),
        ),
    ]
