# Generated by Django 3.2 on 2023-07-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0008_alter_purchase_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='sex',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=256, null=True, verbose_name='Пол'),
        ),
    ]
