# Generated by Django 3.2 on 2023-08-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0009_alter_purchase_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='sex',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default=1, max_length=256, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
