# Generated by Django 3.2 on 2023-08-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0013_auto_20230808_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectfeature',
            name='type',
            field=models.CharField(choices=[('Internet', 'Интернет'), ('Shower', 'Душ'), ('Kitchen', 'Кухня'), ('TV', 'Телевизор'), ('Fridge', 'Холодильник'), ('Conditioner', 'Кондиционер'), ('Playground', 'Детская площадка'), ('Brazier', 'Мангал')], max_length=256, verbose_name='Тип услуги'),
        ),
    ]
