# Generated by Django 3.2 on 2023-08-17 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0014_alter_objectfeature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий закзачика'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='count_adult',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Кол-во взрослых'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='count_kids',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Кол-во детей'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pets',
            field=models.TextField(blank=True, null=True, verbose_name='Инфо о животных'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='telegram',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ник Телеграм'),
        ),
    ]
