# Generated by Django 3.2 on 2023-08-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0016_alter_objectfeature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status_purchase',
            field=models.CharField(choices=[('New', 'Не обработанна'), ('Approved', 'Одобрена'), ('Denied', 'Отклонена'), ('Closed', 'Завершена')], default='New', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
