# Generated by Django 3.2 on 2023-08-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0017_auto_20230825_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='status_purchase',
            new_name='stat',
        ),
    ]
