# Generated by Django 3.2 on 2023-07-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0003_alter_entertainment_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearestplace',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='nearestplace',
            name='location',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Местонахождение'),
        ),
    ]
