# Generated by Django 3.2 on 2023-07-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0004_auto_20230712_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Цена'),
        ),
    ]
