# Generated by Django 3.2 on 2023-06-29 20:59

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20230629_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backphoto',
            name='photo_m',
            field=models.ImageField(default='default\\main.jpg', upload_to='photo_pages', validators=[config.validators.validate_image_size], verbose_name='Фон Главная'),
        ),
    ]
