# Generated by Django 3.2 on 2023-07-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20230712_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyagreement',
            name='agreement',
            field=models.TextField(null=True, verbose_name='Пользовательское соглашение'),
        ),
        migrations.AlterField(
            model_name='policyagreement',
            name='policy',
            field=models.TextField(null=True, verbose_name='Политика конфиденциальности'),
        ),
    ]
