# Generated by Django 3.2 on 2023-08-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20230814_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyagreement',
            options={'verbose_name': 'Политика и соглашение', 'verbose_name_plural': 'Политика и соглашение'},
        ),
    ]
