# Generated by Django 3.2 on 2023-06-12 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_dish_feedinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_changed', models.DateField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Правила',
                'verbose_name_plural': 'Правила',
            },
        ),
        migrations.AlterModelOptions(
            name='feedinginfo',
            options={'verbose_name': 'О питании', 'verbose_name_plural': 'О питании'},
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, auto_now=True, null=True)),
                ('content', models.TextField(max_length=1000, verbose_name='Содержание')),
                ('rules', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='info.rulesinfo')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
            },
        ),
    ]
