# Generated by Django 3.2 on 2023-06-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description_short', models.TextField(max_length=300, verbose_name='Кратко о развлечении')),
                ('description_long', models.TextField(verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Развлечение',
                'verbose_name_plural': 'Развлечения',
            },
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='NearestPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('location', models.TextField(max_length=1000, verbose_name='Местонахождение')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Ближайшие места',
            },
        ),
        migrations.CreateModel(
            name='PhotoNearestPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='photo_nearest_places', verbose_name='Файл')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='entertainments.nearestplace')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='PhotoGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='photo_galery', verbose_name='Файл')),
                ('galeries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='entertainments.galery')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='PhotoEntertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='photo_entertainment', verbose_name='Фото')),
                ('entertainment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='entertainments.entertainment')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='EntertainmentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=256, verbose_name='Услуга')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('entertainment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='entertainments.entertainment')),
            ],
            options={
                'verbose_name': 'Entertainment price',
                'verbose_name_plural': 'Услуги и цены',
            },
        ),
    ]
