# Generated by Django 3.2 on 2023-06-12 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearestPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('location', models.TextField(max_length=1000, verbose_name='Местонахождение')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Ближайшие места',
            },
        ),
        migrations.CreateModel(
            name='PhotoNearestPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='photo_nearest_places', verbose_name='Файл')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='entertainments.nearestplace')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
