# Generated by Django 3.2 on 2023-06-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Internet', 'Интернет'), ('Shower', 'Душ'), ('Kitchen', 'Кухня'), ('TV', 'Телевизор'), ('Fridge', 'Холодильник')], max_length=256)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('pers_num', models.IntegerField(verbose_name='Вместимость')),
                ('description_short', models.TextField(max_length=256, verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Подробное описание')),
                ('price_weekday', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена по будням')),
                ('price_holiday', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена по выходным')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='Занят')),
            ],
            options={
                'verbose_name': 'Домик',
                'verbose_name_plural': 'Домики',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bedroom', 'Спальня'), ('guestroom', 'Гостинная')], max_length=20, verbose_name='Комната')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='object.object')),
            ],
            options={
                'verbose_name': 'Objects room',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО')),
                ('sex', models.CharField(choices=[('m', 'Мужской'), ('w', 'Женский')], max_length=256, verbose_name='Пол')),
                ('passport_country', models.CharField(max_length=256, verbose_name='Гражданство')),
                ('address', models.TextField(verbose_name='Адресс')),
                ('phone_number', models.CharField(max_length=256, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telegram', models.CharField(max_length=256, verbose_name='Ник телеграм')),
                ('desired_arrival', models.DateField(verbose_name='Дата заселения')),
                ('desired_departure', models.DateField(verbose_name='Дата выселения')),
                ('status', models.BooleanField(default=False, verbose_name='Одобрена')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Завершена')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='object.object', verbose_name='Домик')),
                ('was_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='was_purchases', to='object.object', verbose_name='Ранее в заказе')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='PhotoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='photo_object', verbose_name='Файл')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='object.object')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='ObjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Internet', 'Интернет'), ('Shower', 'Душ'), ('Kitchen', 'Кухня'), ('TV', 'Телевизор'), ('Fridge', 'Холодильник')], max_length=256, verbose_name='Тип услуги')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='object.object', verbose_name='Object')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Single Bed', 'Односпальная кровать'), ('Double Bed', 'Двухместная кровать'), ('Queen SizeBed', 'Двухместная кровать широкая'), ('King SizeBed', 'Большая двухместная кровать'), ('Extra Bed', 'Дополнительная кровать'), ('Crib', 'Детская кровать')], max_length=40, verbose_name='Кровать')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='object.object')),
            ],
            options={
                'verbose_name': 'Кровать',
                'verbose_name_plural': 'Кровати',
            },
        ),
    ]
