# Generated by Django 4.2 on 2023-04-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_time', models.TimeField()),
                ('breakfast_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dinner_time', models.TimeField()),
                ('dinner_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('supper_time', models.TimeField()),
                ('supper_cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'feeding',
                'verbose_name_plural': 'feeding',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('pers_num', models.IntegerField()),
                ('description_long', models.TextField()),
                ('price_weekday', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_holiday', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description_short', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bdr', 'Спальня'), ('gst', 'Гостинная')], max_length=3)),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='object.object')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='PhotoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='photo_object', verbose_name='Image')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='object.object')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'image',
            },
        ),
    ]
