# Generated by Django 4.2 on 2023-04-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feeding',
            new_name='FeedingInfo',
        ),
    ]
