# Generated by Django 4.2 on 2023-04-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_rename_feeding_feedinginfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedinginfo',
            options={'verbose_name': 'Feeding info', 'verbose_name_plural': 'Feeding info'},
        ),
        migrations.AlterModelOptions(
            name='photoobject',
            options={'verbose_name': 'Object photo', 'verbose_name_plural': 'Object photos'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Object room', 'verbose_name_plural': 'Object rooms'},
        ),
        migrations.AlterField(
            model_name='object',
            name='description_short',
            field=models.CharField(max_length=500),
        ),
    ]
