# Generated by Django 4.2 on 2023-04-24 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0004_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertaiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Entertaiment',
                'verbose_name_plural': 'Entertaiments',
            },
        ),
        migrations.CreateModel(
            name='PhotoEntertaiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='photo_entertaiment', verbose_name='photo_entertaiment')),
                ('entertaiment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='object.entertaiment')),
            ],
            options={
                'verbose_name': 'Photo of entertaiment',
                'verbose_name_plural': 'Photos of entertaiment',
            },
        ),
    ]
