# Generated by Django 4.2 on 2023-04-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0005_entertaiment_photoentertaiment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoentertaiment',
            options={'verbose_name': 'Entertaiments photo', 'verbose_name_plural': 'Entertaiments photos'},
        ),
        migrations.AlterModelOptions(
            name='photoobject',
            options={'verbose_name': 'Objects photo', 'verbose_name_plural': 'Objects photos'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Objects room', 'verbose_name_plural': 'Objects rooms'},
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='feature_icons', verbose_name='features_icon')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='object.object')),
            ],
            options={
                'verbose_name': 'Objects_feature',
                'verbose_name_plural': 'Objects_features',
            },
        ),
    ]
