# Generated by Django 4.2 on 2023-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0006_alter_photoentertaiment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='title',
        ),
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.CharField(choices=[('Internet', 'Интернет'), ('Shower', 'Душ'), ('Kitchen', 'Кухня'), ('TV', 'Телевизор'), ('Fridge', 'Холодильник')], default=1, max_length=256),
            preserve_default=False,
        ),
    ]
