# Generated by Django 4.2 on 2023-04-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0007_remove_feature_title_feature_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='object_id',
        ),
    ]
