# Generated by Django 4.2 on 2023-04-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0009_alter_feature_options_objectfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='object_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='object.object'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ObjectFeature',
        ),
    ]
