# Generated by Django 4.2 on 2023-04-25 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0010_feature_object_id_delete_objectfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='object_id',
        ),
        migrations.CreateModel(
            name='ObjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Internet', 'Интернет'), ('Shower', 'Душ'), ('Kitchen', 'Кухня'), ('TV', 'Телевизор'), ('Fridge', 'Холодильник')], max_length=256)),
                ('feature_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='object_feature', to='object.feature')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='object.object')),
            ],
            options={
                'verbose_name': 'Objects_feature',
                'verbose_name_plural': 'Objects_features',
            },
        ),
    ]
