# Generated by Django 4.2 on 2023-04-25 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0011_remove_feature_object_id_objectfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectfeature',
            name='feature_id',
        ),
        migrations.AlterField(
            model_name='objectfeature',
            name='object_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='object.object', verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='photoobject',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='photo_object', verbose_name='Photos file'),
        ),
    ]
