# Generated by Django 4.2 on 2023-04-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0012_remove_objectfeature_feature_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.AlterModelOptions(
            name='objectfeature',
            options={'verbose_name': 'Objects feature', 'verbose_name_plural': 'Objects features'},
        ),
    ]
