# Generated by Django 4.2 on 2023-04-28 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0014_info_social_phonenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'Info phone number', 'verbose_name_plural': 'Info phone numbers'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Social', 'verbose_name_plural': 'Socials'},
        ),
        migrations.RemoveField(
            model_name='social',
            name='info',
        ),
        migrations.RemoveField(
            model_name='social',
            name='title',
        ),
        migrations.AddField(
            model_name='social',
            name='type',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram')], default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='InfoSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram')], max_length=256)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='object.info', verbose_name='info')),
            ],
            options={
                'verbose_name': 'Info social',
                'verbose_name_plural': 'Info socials',
            },
        ),
    ]
