# Generated by Django 4.2 on 2023-04-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0015_alter_phonenumber_options_alter_social_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosocial',
            name='link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
