# Generated by Django 4.2 on 2023-04-28 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0016_infosocial_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='object.info', verbose_name='phone'),
        ),
    ]
