# Generated by Django 4.2 on 2023-05-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0018_alter_object_options_object_created_date_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300)),
                ('sex', models.CharField(choices=[('m', 'Мужской'), ('w', 'Женский')], max_length=256)),
                ('passport_country', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('telegram', models.CharField(max_length=256)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='object.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
