# Generated by Django 4.2 on 2023-05-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0019_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='description_long',
            field=models.TextField(verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='object',
            name='description_short',
            field=models.TextField(max_length=256, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='object',
            name='pers_num',
            field=models.IntegerField(verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='object',
            name='price_holiday',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена по выходным'),
        ),
        migrations.AlterField(
            model_name='object',
            name='price_weekday',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена по будням'),
        ),
        migrations.AlterField(
            model_name='object',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
