# Generated by Django 4.2 on 2023-05-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0022_alter_photoobject_options_alter_object_is_reserved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectfeature',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='entertaiment',
            name='description_long',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entertaiment',
            name='description_short',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='beds_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objectfeature',
            name='type',
            field=models.CharField(choices=[('Internet', 'Интернет'), ('Shower', 'Душ'), ('Kitchen', 'Кухня'), ('TV', 'Телевизор'), ('Fridge', 'Холодильник')], max_length=256, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='photoobject',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='photo_object', verbose_name='Файл'),
        ),
    ]
