# Generated by Django 4.2 on 2023-05-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0023_alter_objectfeature_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='icon',
        ),
    ]
