# Generated by Django 4.2 on 2023-05-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0024_remove_feature_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertaiment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entertaiment',
            name='price_desription',
            field=models.CharField(default=15.0, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entertaiment',
            name='description_short',
            field=models.TextField(max_length=300),
        ),
    ]
