# Generated by Django 4.2 on 2023-05-16 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0026_purchase_desired_arrival_purchase_desired_departure'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntertimentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Entertaiment Price',
                'verbose_name_plural': 'Entertaiments Prices',
            },
        ),
        migrations.RemoveField(
            model_name='entertaiment',
            name='price',
        ),
        migrations.AddField(
            model_name='entertaiment',
            name='prices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entertaiment', to='object.entertimentprice'),
        ),
    ]
