# Generated by Django 4.2 on 2023-05-17 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0027_entertimentprice_remove_entertaiment_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertaiment',
            name='prices',
        ),
        migrations.AddField(
            model_name='entertimentprice',
            name='entertaiments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='object.entertaiment'),
            preserve_default=False,
        ),
    ]
