# Generated by Django 4.2 on 2023-05-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0028_remove_entertaiment_prices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entertimentprice',
            options={'verbose_name': 'Entertaiment price', 'verbose_name_plural': 'Entertaiments prices'},
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sng', 'Односпальная кровать'), ('dbl', 'Двухместная кровать'), ('qsz', 'Двухместная кровать широкая'), ('kzb', 'Большая двухместная кровать'), ('exb', 'Дополнительная кровать'), ('crb', 'Детская кровать')], max_length=4)),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='beds', to='object.object')),
            ],
        ),
    ]
