# Generated by Django 4.2 on 2023-05-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0031_nearestplace_alter_galery_options_alter_galery_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearestplace',
            name='location',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
