# Generated by Django 4.2 on 2023-05-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0032_nearestplace_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
        migrations.RemoveField(
            model_name='entertaiment',
            name='price_desription',
        ),
        migrations.RemoveField(
            model_name='object',
            name='beds_count',
        ),
    ]
