# Generated by Django 4.2 on 2023-06-06 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0033_delete_social_remove_entertaiment_price_desription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_changed', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Правила',
                'verbose_name_plural': 'Правила',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bed',
            options={'verbose_name': 'Кровать', 'verbose_name_plural': 'Кровати'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информация'},
        ),
        migrations.AlterModelOptions(
            name='infosocial',
            options={'verbose_name': 'Соц. сеть', 'verbose_name_plural': 'Соц. сети'},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Objects room', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'Правило', 'verbose_name_plural': 'Правила'},
        ),
        migrations.AlterField(
            model_name='bed',
            name='type',
            field=models.CharField(choices=[('Single Bed', 'Односпальная кровать'), ('Double Bed', 'Двухместная кровать'), ('Queen SizeBed', 'Двухместная кровать широкая'), ('King SizeBed', 'Большая двухместная кровать'), ('Extra Bed', 'Дополнительная кровать'), ('Crib', 'Детская кровать')], max_length=40, verbose_name='Кровать'),
        ),
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.TextField(max_length=1000, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='info',
            name='comment',
            field=models.TextField(max_length=1000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='info',
            name='geolocation',
            field=models.TextField(max_length=1000, verbose_name='Геолокация'),
        ),
        migrations.AlterField(
            model_name='infosocial',
            name='type',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram')], max_length=256, verbose_name='Соц. сеть'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone',
            field=models.CharField(max_length=256, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('bedroom', 'Спальня'), ('guestroom', 'Гостинная')], max_length=20, verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='rule',
            name='rules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='object.rulesinfo'),
        ),
    ]
