# Generated by Django 4.2 on 2023-06-06 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0034_rulesinfo_test_alter_bed_options_alter_info_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
