# Generated by Django 3.2 on 2023-06-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0035_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesinfo',
            name='was_changed',
            field=models.DateField(auto_now=True, verbose_name='Изменено'),
        ),
    ]
