# Generated by Django 3.2 on 2023-06-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0036_alter_rulesinfo_was_changed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entertaiment',
            options={'verbose_name': 'Развлечение', 'verbose_name_plural': 'Развлечения'},
        ),
        migrations.AlterModelOptions(
            name='entertimentprice',
            options={'verbose_name': 'Entertaiment price', 'verbose_name_plural': 'Услуги и цены'},
        ),
        migrations.AlterModelOptions(
            name='photoentertaiment',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterField(
            model_name='entertaiment',
            name='description_long',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='entertaiment',
            name='description_short',
            field=models.TextField(max_length=300, verbose_name='Кратко о развлечении'),
        ),
        migrations.AlterField(
            model_name='entertaiment',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='entertimentprice',
            name='header',
            field=models.CharField(max_length=256, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='entertimentprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='feedinginfo',
            name='breakfast_cost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6),
        ),
        migrations.AlterField(
            model_name='feedinginfo',
            name='breakfast_time',
            field=models.TimeField(default='09:00[:00[.000000]]'),
        ),
        migrations.AlterField(
            model_name='feedinginfo',
            name='dinner_cost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6),
        ),
        migrations.AlterField(
            model_name='feedinginfo',
            name='dinner_time',
            field=models.TimeField(default='12:00[:00[.000000]]'),
        ),
        migrations.AlterField(
            model_name='feedinginfo',
            name='supper_cost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6),
        ),
        migrations.AlterField(
            model_name='feedinginfo',
            name='supper_time',
            field=models.TimeField(default='18:00[:00[.000000]]'),
        ),
        migrations.AlterField(
            model_name='photoentertaiment',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='photo_entertaiment', verbose_name='Фото'),
        ),
    ]
