# Generated by Django 3.2 on 2023-06-10 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0037_auto_20230609_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedinginfo',
            options={'verbose_name': 'Питание', 'verbose_name_plural': 'Питание'},
        ),
        migrations.AddField(
            model_name='dish',
            name='feeding',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='object.feedinginfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedinginfo',
            name='breakfast_cost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6, verbose_name='Стоимость завтрака, руб'),
        ),
        migrations.AlterField(
            model_name='feedinginfo',
            name='breakfast_time',
            field=models.TimeField(default='09:00[:00[.000000]]', verbose_name='Время завтрака'),
        ),
        migrations.AlterField(
            model_name='feedinginfo',
            name='dinner_cost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6, verbose_name='Стоимость обеда, руб'),
        ),
        migrations.AlterField(
            model_name='feedinginfo',
            name='dinner_time',
            field=models.TimeField(default='12:00[:00[.000000]]', verbose_name='Время обеда'),
        ),
        migrations.AlterField(
            model_name='feedinginfo',
            name='supper_cost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6, verbose_name='Стоимость ужина, руб'),
        ),
        migrations.AlterField(
            model_name='feedinginfo',
            name='supper_time',
            field=models.TimeField(default='18:00[:00[.000000]]', verbose_name='Время ужина'),
        ),
    ]
