# Generated by Django 3.2 on 2023-06-11 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0038_auto_20230610_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Кухня'},
        ),
        migrations.AlterModelOptions(
            name='feedinginfo',
            options={'verbose_name': 'Информация о питании', 'verbose_name_plural': 'Информации о питании'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Общая информация', 'verbose_name_plural': 'Общая информация'},
        ),
        migrations.AlterModelOptions(
            name='photonearestplace',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AddField(
            model_name='rule',
            name='created_at',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo_dish', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='nearestplace',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='nearestplace',
            name='location',
            field=models.TextField(max_length=1000, verbose_name='Местонахождение'),
        ),
        migrations.AlterField(
            model_name='nearestplace',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='address',
            field=models.TextField(verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='desired_arrival',
            field=models.DateField(verbose_name='Дата заселения'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='desired_departure',
            field=models.DateField(verbose_name='Дата выселения'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='fio',
            field=models.CharField(max_length=300, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='object.object', verbose_name='Домик'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='passport_country',
            field=models.CharField(max_length=256, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='phone_number',
            field=models.CharField(max_length=256, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='sex',
            field=models.CharField(choices=[('m', 'Мужской'), ('w', 'Женский')], max_length=256, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='telegram',
            field=models.CharField(max_length=256, verbose_name='Ник телеграм'),
        ),
    ]
