# Generated by Django 3.2 on 2023-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0039_auto_20230611_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='created_at',
            field=models.DateField(auto_created=True, auto_now=True, null=True),
        ),
    ]
