# Generated by Django 3.2 on 2023-06-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0040_alter_rule_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertimentprice',
            name='entertaiments',
        ),
        migrations.RemoveField(
            model_name='photoentertaiment',
            name='entertaiment_id',
        ),
        migrations.RemoveField(
            model_name='photonearestplace',
            name='places',
        ),
        migrations.DeleteModel(
            name='Entertaiment',
        ),
        migrations.DeleteModel(
            name='EntertimentPrice',
        ),
        migrations.DeleteModel(
            name='NearestPlace',
        ),
        migrations.DeleteModel(
            name='PhotoEntertaiment',
        ),
        migrations.DeleteModel(
            name='PhotoNearestPlace',
        ),
    ]
