# Generated by Django 3.2 on 2023-06-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0041_auto_20230612_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogalery',
            name='galeries',
        ),
        migrations.DeleteModel(
            name='Galery',
        ),
        migrations.DeleteModel(
            name='PhotoGalery',
        ),
    ]
