# Generated by Django 3.2 on 2023-06-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0042_auto_20230612_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infosocial',
            name='info',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='info',
        ),
        migrations.AlterModelOptions(
            name='feedinginfo',
            options={'verbose_name': 'Информация о питании', 'verbose_name_plural': 'Информация о питании'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Домик', 'verbose_name_plural': 'Домики'},
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='InfoSocial',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
