# Generated by Django 3.2 on 2023-06-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0043_auto_20230612_2021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='FeedingInfo',
        ),
    ]
