# Generated by Django 3.2 on 2023-06-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0045_auto_20230612_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Занят'),
        ),
    ]
