# Generated by Django 3.2 on 2023-06-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0046_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Одобрена'),
        ),
    ]
