# Generated by Django 3.2 on 2023-06-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0047_alter_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Одобрена'),
        ),
    ]
