# Generated by Django 3.2 on 2023-06-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0048_alter_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Завершена'),
        ),
    ]
