# Generated by Django 3.2 on 2023-06-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0049_purchase_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='was_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='was_purchases', to='object.object', verbose_name='Домик'),
            preserve_default=False,
        ),
    ]
